# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=21)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
                ('certification', models.FileField(blank=True, null=True, upload_to=b'')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Coach/profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('independent', 'independent'), ('Coach-Dependent', 'Coach-Dependent')], max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=21)),
                ('homestate', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=20)),
                ('height_feet', models.CharField(choices=[('1ft', '1ft'), ('2ft', '2ft'), ('3ft', '3ft'), ('4ft', '4ft'), ('5ft', '5ft'), ('6ft', '6ft')], max_length=3)),
                ('height_inches', models.CharField(choices=[('1in', '1in'), ('2in', '2in'), ('3in', '3in'), ('4in', '4in'), ('5in', '5in'), ('6in', '6in'), ('7in', '7in'), ('8in', '8in'), ('9in', '9in'), ('10in', '10in'), ('11in', '11in'), ('12in', '12in')], max_length=4)),
                ('weight', models.CharField(max_length=3)),
                ('batting_orientation', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=50)),
                ('position', models.CharField(choices=[('pitcher', 'pitcher'), ('catcher', 'catcher'), ('first base', 'first base'), ('second base', 'second base'), ('third base', 'third base'), ('shortstop', 'shortstop'), ('right fielder', 'right fielder'), ('left fielder', 'left fielder'), ('center fielder', 'center fielder')], max_length=50)),
                ('player_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swing_name', models.CharField(max_length=50)),
                ('start_rot_x', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_rot_x', models.DecimalField(decimal_places=3, max_digits=200)),
                ('start_rot_y', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_rot_y', models.DecimalField(decimal_places=3, max_digits=200)),
                ('start_rot_z', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_rot_z', models.DecimalField(decimal_places=3, max_digits=200)),
                ('start_pos_x', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_pos_x', models.DecimalField(decimal_places=3, max_digits=200)),
                ('start_pos_y', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_pos_y', models.DecimalField(decimal_places=3, max_digits=200)),
                ('start_pos_z', models.DecimalField(decimal_places=3, max_digits=200)),
                ('end_pos_z', models.DecimalField(decimal_places=3, max_digits=200)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=300)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('mascot', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=21)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Team'),
        ),
    ]
