# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='resume',
        ),
    ]
