# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170426_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swings',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
